# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm_planner
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - rot_joint
    - vert_joint
    - hor_link
    - grip_rot_joint
    - gripper_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_planner_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - rot_joint
      - vert_joint
      - hor_link
      - grip_rot_joint
      - gripper_joint
arm_planner_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - rot_joint
    - vert_joint
    - hor_link
    - grip_rot_joint
    - gripper_joint
  gains:
    rot_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    vert_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    hor_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    grip_rot_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    gripper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1